In [1]:
#1. Create Two numpy array of size 3 X 2 and 2 X 3

import numpy as np
import pandas as pd
arr1 = np.empty(shape = (3,2) )
arr2 = np.empty(shape = (2,3) )
print(arr1)
print("\n")
print(arr2)

[[4.68078652e-310 0.00000000e+000]
 [3.74165235e+233 2.41794167e+198]
 [1.02615684e+160 1.04990471e-153]]


[[4.68078647e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

In [3]:
# 2. Randomly Initalize that array

arr = np.array(list(range(5,11)))
arr1 = arr.reshape(3,2)
arr2 = arr.reshape(2,3)
print("First array:\n",arr1)
print("Second array:\n",arr2)

First array:
 [[ 5  6]
 [ 7  8]
 [ 9 10]]
Second array:
 [[ 5  6  7]
 [ 8  9 10]]

In [4]:
#3. Perform matrix multiplication
mul = np.dot(arr1, arr2)
mul

array([[ 73,  84,  95],
       [ 99, 114, 129],
       [125, 144, 163]])

In [5]:
#4. Perform elementwise matrix multiplication
result_1 = arr1 * arr2.T
result_2 = arr1.T * arr2
print(result_1, "\n",result_2)

[[ 25  48]
 [ 42  72]
 [ 63 100]]
 [[ 25  42  63]
 [ 48  72 100]]

In [6]:
#5. Find mean of first matrix
mean1 = np.mean(arr1)
print(mean1)

7.5

In [7]:
#6. Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
data = pd.read_csv(r"mtcars.csv")
print(data.shape)
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'mtcars.csv'

In [8]:
data = pd.read_csv(r"mtcars.csv")
print(data.shape)
data.head()

(32, 12)

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
def centered_mean(column):
    arr = np.array(column)
    arr = arr - np.mean(arr)
    return pd.DataFrame(arr)

In [10]:
data_columns = data.columns
for i in range(1,12):
    data[data_columns[i]] = centered_mean(data[data_columns[i]])

In [11]:
data.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,0.909375,-0.1875,-70.721875,-36.6875,0.303437,-0.59725,-1.38875,-0.4375,0.59375,0.3125,1.1875
1,Mazda RX4 Wag,0.909375,-0.1875,-70.721875,-36.6875,0.303437,-0.34225,-0.82875,-0.4375,0.59375,0.3125,1.1875
2,Datsun 710,2.709375,-2.1875,-122.721875,-53.6875,0.253437,-0.89725,0.76125,0.5625,0.59375,0.3125,-1.8125
3,Hornet 4 Drive,1.309375,-0.1875,27.278125,-36.6875,-0.516563,-0.00225,1.59125,0.5625,-0.40625,-0.6875,-1.8125
4,Hornet Sportabout,-1.390625,1.8125,129.278125,28.3125,-0.446563,0.22275,-0.82875,-0.4375,-0.40625,-0.6875,-0.8125

In [12]:
data.tail()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,10.309375,-2.1875,-135.621875,-33.6875,0.173437,-1.70425,-0.94875,0.5625,0.59375,1.3125,-0.8125
28,Ford Pantera L,-4.290625,1.8125,120.278125,117.3125,0.623437,-0.04725,-3.34875,-0.4375,0.59375,1.3125,1.1875
29,Ferrari Dino,-0.390625,-0.1875,-85.721875,28.3125,0.023438,-0.44725,-2.34875,-0.4375,0.59375,1.3125,3.1875
30,Maserati Bora,-5.090625,1.8125,70.278125,188.3125,-0.056563,0.35275,-3.24875,-0.4375,0.59375,1.3125,5.1875
31,Volvo 142E,1.309375,-2.1875,-109.721875,-37.6875,0.513438,-0.43725,0.75125,0.5625,0.59375,0.3125,-0.8125